### ISSUE TITLE
S52 symbol

### ISSUE THREAD

**Issue by oliveever** [manimaul/njord#45]
From this file[S-52_PresLib Ed 4.0.3 Part I Addendum_Clean.pdf](https://github.com/manimaul/njord/blob/master/docs/reference_material/s52_s57_spec/S-52_PresLib%20Ed%204.0.3%20Part%20I%20Addendum_Clean.pdf) it can be seen that there are many s52 symbols, and drawing them one by one will take a major expenditure of time and effort.

The [chartsymbols.xml](https://github.com/manimaul/njord/blob/master/docs/reference_material/opencpn/chartsymbols.xml) file contains hpgl vector icon information and related attributes. I tried to convert hpgl to png, and it failed. But why can opencpn read it?

Do you have any other ways to obtain symbols?

https://github.com/manimaul/njord/tree/master/docs/reference_material/hpgl

**Comment by manimaul** [comment]
I should add that right now most of the sprites we use are extracted from the OpenCPN sprite sheet:
https://github.com/manimaul/njord/blob/master/docs/reference_material/opencpn/chartsymbolextractor.py

This is a short term solution. I think the long term solution is to have svg files and a script to compile a sprite sheet.
I've started this here: https://github.com/manimaul/njord/tree/master/sprites

Additionally I plan on using the single distance field feature: https://maplibre.org/maplibre-style-spec/sprite/ for many if not all of the sprites so that they can be dynamically colorized.

**Comment by manimaul** [comment]
@oliveever - yeah, the script kind assumes a few things such as having Docker, inkscape & scour installed. It also assumes that you've built the Dockerfile into a container named hpgl.

Perhaps it would be better to move the sprite symbol creation to it's own repo. Here I've put made the extraction process a bit better and put all of the generated svg files in this repo: https://github.com/manimaul/s52-sprites

The svg symbols are pretty raw and I'll need to tune their scale before constructing a new sprite sheet with them.
